### ISSUE TITLE
.png files in zip release are corrupted

### ISSUE THREAD

**Issue by mikemonteith** [nhsuk/nhsuk-frontend#1009]
# Bug Report

The .png files inside the github .zip release seem to be corrupted.

![image](https://github.com/user-attachments/assets/2e8b0c05-52a3-4912-bf0f-6d65f53ad072)

## To reproduce:

1. Go to the latest release: https://github.com/nhsuk/nhsuk-frontend/releases/tag/v8.3.0
2. Go to the "Assets" section
3. Download the nhsuk-frontend-8.3.0.zip file
4. Unzip
5. Open any of the .png files

**Comment by frankieroberto** [comment]
@mikemonteith odd! They're fine [in the source](https://github.com/nhsuk/nhsuk-frontend/tree/v8.3.0/packages/assets/logos), so must be something up with the release process... 🤔

**Comment by mikemonteith** [comment]
I've copied the files out of the source and they are working fine. Something up with the gulp zip tasks probably.
Now who created that... 🙈 
![image](https://github.com/user-attachments/assets/740beca6-ddb3-4218-a9fd-54700bc7b4cb)

**Comment by chrimesdev** [comment]
Gulp v5.0 https://github.com/gulpjs/gulp/issues/2777#issuecomment-2036776560

**Comment by frankieroberto** [comment]
I can repeat it locally by running `npm run build-gh-release` which runs the gulp zip process.
