### ISSUE TITLE
Add a config option for the assets URL

### ISSUE THREAD

**Issue by mikemonteith** [nhsuk/nhsuk-frontend#135]
All assets referenced by the CSS are at `/assets/*`.
Some people might not be able to host at this location.
We should add a configuration option in sass so that the base url can be used.

What base url do other CSS frameworks use in the compiled version? Maybe a relative path would be best for the default compiled css.

**Comment by AdamChrimes** [comment]
We will also need to the config option for asset path for the NHS SVG logo fallback for IE8

```html
 <image xlink:href="" src="/assets/logos/fallback/logo-nhs.png"></image>
```

Currently it points at `/assets/logos/fallback/logo-nhs.png` but people might not have their assets hosted at the same location. 

May be more difficult to do as its a SVG file we need to put the asset path URL in, do we move the SVG fallback to CSS?

**Comment by mikemonteith** [comment]
Could use relative path instead for the svg? If someone can host an .svg, they can probably host a .png  somewhere relative to it.

**Comment by mikemonteith** [comment]
Closed because we are avoiding the use of `url(...)` in our CSS for now.
We only had one background-image, so we will use a base64 encoded string.

For future reference, we shouldn't be using too many base64-encoded strings in our CSS for css-weight reasons. If we get many more background-image icons, this ticket might need to get reopened.
