### ISSUE TITLE
Harry Roberts workshop - Code review

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-frontend#138]
Key selector 

- [ ] .nhsuk-icon__chevron-down path {
- [ ] .nhsuk-icon__chevron-up path {
- [ ] .nhsuk-list--check svg,.nhsuk-list--cross svg {
- [ ] .nhsuk-c-action-link:focus span {
- [ ] .nhsuk-c-action-link:hover span {
- [ ] .nhsuk-c-care-card--black .nhsuk-c-care-card__content a {
- [ ] .nhsuk-details__text p {
- [ ] .nhsuk-c-global-alert a {
- [x] .nhsuk-footer__logo a {
- [ ] .suggestions-item:focus div,.suggestions-item:hover div {
- [ ] .suggestions-item--selected a {
- [x] .nhsuk-c-pagination a {
- [x] .nhsuk-c-pagination a {

Core

- [x] Sass comments for files that do not generate CSS
- [x] Comment spacing - alignment
- [x] Font face - move from settings to generic
- [x] Variables - use of !default - base font margin 8px
- [ ] Exports - Figure out what it does - if using it then it needs adding to each components Sass file
- [ ] 'Magic numbers' - ack (need to install) - `$ ack -l --sass '\dpx`'
- [x] Breakpoint name @mixin - mq - govuk
- [ ] Replace all instances of `govuk-media-query` with `mq`.
- [x] Tools Typography - "These mixins allow us to quickly and consistently generate common text patterns such as colours..."
- [ ]  Mobile first MQ's
- [ ] Minus number Sass spacing map 
- [x] Change colour to color
- [x] Change class name .active to .is-active
- [ ] Core components and UI components
- [x] Utilities need u- adding
- [x] Utilities - top-and-bottom needs deleting

Components

- [ ] Care card heading margin: 0; should be margin-bottom: 0;
- [ ] Check shorthand margin/padding.background declarations - `$ ack --sass '(background|margin|padding`):'
- [ ] Instance of !important - look at doing it another way eg: .foo.foo (`$ ack --ignore-dir=packages/core/utilities/ --sass '\!important;'`)
- [ ] SVG assest path variable
- [x] `-9999px` replacement: http://www.zeldman.com/2012/03/01/replacing-the-9999px-hack-new-image-replacement/
- [x] Footer list `&:last-child` should be `> &:last-child` - should be probably for all `&:last-child`
- [ ] Header - break into smaller files
- [ ] Header - large desktop media query - should we re-arrange it?
- [ ] Sass comments - new section with Sass file should restart comments number (1, 2, 3) - not (6, 7, 8)
- [ ] Hero - make comments on 'random numbers' eg: 240px
- [ ] Image component - 'syntax sugar' - `& + &`
- [ ] Back to top - make a decision on whether we keep it or not
- [x] Pagination `<a>` could do with changing a class - eg: `nhsuk-pagination__link`
- [ ] @mixin panel could be renamed to save confusion
- [ ] Panel - need to nest `.panel-group & { }` - "key selector should only appear once".
- [x] Skip link - `-9999px` needs replacing (see above)
- [ ] Table - nest table responsive into table.

Assets

- [x] Icons - change logo to `logo-nhs`

**Comment by AdamChrimes** [comment]
Potentially breaking changes:

- Change colour to color
-  Nav A-Z - BEM naming - trim down names eg: link
-  Name change a-z-nav to nav-a-z
-  SVG assest path variable
-  New name for do and dont list - list-do-dont (Speak to Dean about naming)
-  Feedback banner - rename to Banner feedback (always name from big to small)
-  Global alert - rename to Alert global (always name from big to small)
-  Back to top - make a decision on whether we keep it or not
-  Pagination <a> could do with changing a class - eg: nhsuk-pagination__link

**Comment by mcheung-nhs** [comment]
Done some reading regarding the -9999px hiding and the Kellum method suggested doesn't apply to how we are using it in the skip links styling. The method is used for image replacement, which we are not doing, so keeping our version.
