### ISSUE TITLE
Action link

### ISSUE THREAD

**Issue by AdamChrimes** [nhsuk/nhsuk-frontend#157]
# Action link

Use this issue to discuss the **Action link** component.

[Preview the action link component](https://nhsuk.github.io/nhsuk-frontend/components/action-link.html)

Find out more about the action link component and when to use it in the [NHS Digital service manual](https://beta.nhs.uk/service-manual/patterns/).

See our [contributing guidelines](https://github.com/nhsuk/nhsuk-frontend/tree/master/docs/contributing)

**Comment by davidhunter08** [comment]
Nunjucks macro classes parameter needs removing from 'nhsuk-action-link__link` and adding to `nhsuk-action-link` instead.

**Comment by AdamChrimes** [comment]
Closing these individual placeholder issues. 

Please use the [NHS digital service manual backlog]https://github.com/nhsuk/nhsuk-service-manual-backlog/issues] to discuss this component or raise an issue on the [NHS.UK frontend issues](https://github.com/nhsuk/nhsuk-frontend/issues/new) if you're having issues with the code for this component.
