### ISSUE TITLE
Add syntax highlighting to docs built from markdown

### ISSUE THREAD

**Issue by mikemonteith** [nhsuk/nhsuk-frontend#159]
Github-flavour markdown can use syntax highlighting with a code after three backticks, e.g

    ```html
    <p class="code">syntax highlighting</p>
    ```
resulting in:
```html
<p class="code">syntax highlighting</p>
```

---

We should enable this syntax highlighting in our own built documentation

**Comment by AdamChrimes** [comment]
This has been done for the majority of markdown files.
