### ISSUE TITLE
Details

### ISSUE THREAD

**Issue by AdamChrimes** [nhsuk/nhsuk-frontend#162]
# Details

Use this issue to discuss the **Details** component.

[Preview the details component](https://nhsuk.github.io/nhsuk-frontend/components/details.html)

Find out more about the action link component and when to use it in the [NHS Digital service manual](https://beta.nhs.uk/service-manual/patterns/).

See our [contributing guidelines](https://github.com/nhsuk/nhsuk-frontend/tree/master/docs/contributing)

**Comment by beseven** [comment]
We've used the details component to update the reveal and Q&A wagtail components on the nhsuk-live as we discussed previously. 
As these particular components allow a markdown component, we had to target the styling of multiple HTML elements to make them fit in with the rest of the styling. As this just a small step prior to integrating the FE library with the project, we wanted to share our learning. Please take a look at the PR and let us know if this is of use to you: https://github.com/nhsuk/nhsuk-frontend/pull/363

**Comment by AdamChrimes** [comment]
Closing these individual placeholder issues. 

Please use the [NHS digital service manual backlog](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues) to discuss the usage of this component. If you're having trouble with the code, or have found a bug, please [raise an issue on the NHS.UK frontend backlog](https://github.com/nhsuk/nhsuk-frontend/issues/new)
