### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by AdamChrimes** [nhsuk/nhsuk-frontend#169]
# Header

Use this issue to discuss the **Header** component.

[Preview the header component](https://nhsuk.github.io/nhsuk-frontend/components/header.html)
[Preview the transactional header component](https://nhsuk.github.io/nhsuk-frontend/components/header-transactional.html)
[Preview the header with navigation only component](https://nhsuk.github.io/nhsuk-frontend/components/header-search.html)
[Preview the header with search only component](https://nhsuk.github.io/nhsuk-frontend/components/header-search.html)

Find out more about the header component and when to use it in the [NHS Digital service manual](https://beta.nhs.uk/service-manual/patterns/).

See our [contributing guidelines](https://github.com/nhsuk/nhsuk-frontend/tree/master/docs/contributing)

**Comment by davidhunter08** [comment]
There is an issue with the menu button placement in the header when a 'long' service name is used.

![screencapture-xlasercut-github-io-nhsuk-frontend-vue-2019-04-08-09_52_26](https://user-images.githubusercontent.com/14331000/55711976-c4769780-59e5-11e9-8a7a-d280f40471ba.png)

The code can be seen at https://xlasercut.github.io/nhsuk-frontend-vue/

This has also highlighted the issue of the menu button placement when there is no search button. 

![header-no-search](https://user-images.githubusercontent.com/14331000/55712752-3ac7c980-59e7-11e9-95e2-825d4dc5f8d7.png)

<img width="1243" alt="header-no-search-inspect" src="https://user-images.githubusercontent.com/14331000/55712759-3dc2ba00-59e7-11e9-911f-65aacf384e2e.png">

The menu button should align right (of the container) when there is no search button.

<img width="453" alt="header-no-search-aligned" src="https://user-images.githubusercontent.com/14331000/55712775-44513180-59e7-11e9-98d7-f54bb5f16c81.png">

**Comment by damonjagger** [comment]
Some of the NHS services I work on use a different [organisational logo](https://www.england.nhs.uk/nhsidentity/identity-guidelines/organisational-logos/).

It would be useful if we could extend the logo part of the header for those services.

I haven't done any testing to see what the impact of doing this would be in the current iteration of the header component. But it's [something I'd like to see in the wagtail nhsuk frontend](https://github.com/nhsuk/wagtail-nhsuk-frontend/issues/132).

**Comment by AdamChrimes** [comment]
Closing these individual placeholder issues. 

Please use the [NHS digital service manual backlog](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues) to discuss the usage of this component. If you're having trouble with the code, or have found a bug, please [raise an issue on the NHS.UK frontend backlog](https://github.com/nhsuk/nhsuk-frontend/issues/new)
