### ISSUE TITLE
Hero

### ISSUE THREAD

**Issue by AdamChrimes** [nhsuk/nhsuk-frontend#170]
# Hero

Use this issue to discuss the **Hero** component.

[Preview the hero component](https://nhsuk.github.io/nhsuk-frontend/components/hero.html)
[Preview the hero image component](https://nhsuk.github.io/nhsuk-frontend/components/hero-image.html)
[Preview the hero with content and image component](https://nhsuk.github.io/nhsuk-frontend/components/hero-image-content.html)

Find out more about the hero component and when to use it in the [NHS Digital service manual](https://beta.nhs.uk/service-manual/patterns/).

See our [contributing guidelines](https://github.com/nhsuk/nhsuk-frontend/tree/master/docs/contributing)

**Comment by davidhunter08** [comment]
Classes parameters need adding to nhsuk-hero so that overriding classes can be applied.

**Comment by AdamChrimes** [comment]
Closing these individual placeholder issues. 

Please use the [NHS digital service manual backlog](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues) to discuss the usage of this component. If you're having trouble with the code, or have found a bug, please [raise an issue on the NHS.UK frontend backlog](https://github.com/nhsuk/nhsuk-frontend/issues/new)
