### ISSUE TITLE
Add usage documentation for the grid

### ISSUE THREAD

**Issue by mikemonteith** [nhsuk/nhsuk-frontend#192]
As a developer looking to quickly set up a site,
I don't know how to use the grid.

- Which divs and classes do I need to get a nice layout?
- What considerations for responsive design should I be making?
- Where should I use `<main>`, `<section>`, `<article>`?

**Comment by mikemonteith** [comment]
We could also add nunjucks macros:

```
{% macro grid() %}
  <div class="nhsuk-grid-column-two-thirds">
    <div class="nhsuk-page-content">
      {{ caller() }}
    </div>
  </div>
{% endmacro %}
```

```
{% call grid() -%}
     <p>This is some content to go inside the grid</p>
{%- endcall %}
```

**Comment by nervewax** [comment]
@mikemonteith See [here](https://beta.nhs.uk/service-manual/styles-components-patterns/grid) for some information about the grid and responsive breakpoints.

Regarding HTML5 tags, [this](http://html5doctor.com/downloads/h5d-sectioning-flowchart.png) is a good resource. But I can't speak for the nhsuk specific implementations.

**Comment by mikemonteith** [comment]
Closing this issue because docs are now in the service manual.
