### ISSUE TITLE
Add href config to the header template

### ISSUE THREAD

**Issue by mikemonteith** [nhsuk/nhsuk-frontend#193]
Add a config option so that the NHS logo in the header can link to somewhere other than `/`.  
Example use case: https://nhsuk.github.io/nhsuk-frontend/ should link to `/nhsuk-frontend/` instead of `/`.

Q: Is this ever going to be an issue for anyone else?

**Comment by AdamChrimes** [comment]
I can see this being needed in transactional headers, people may want to link back to the start page of the transaction rather than the NHS Homepage

**Comment by AdamChrimes** [comment]
This work has been done in PR https://github.com/nhsuk/nhsuk-frontend/pull/208
