### ISSUE TITLE
Scss comments being outputted in compiled CSS

### ISSUE THREAD

**Issue by AdamChrimes** [nhsuk/nhsuk-frontend#194]
Comments intended for use in the scss files only are being outputted in the compiled CSS file. We should use the correct scss comment syntax so these comments are not outputted. 

http://sass-lang.com/documentation/file.SCSS_FOR_SASS_USERS.html#Comments

`//` for scss only comments
`/*` for scss and css comments

Need to decide what comments we do want outputting CSS, if any?

**Comment by mcheung-nhs** [comment]
Changes done and merged. Closing this issue.
