### ISSUE TITLE
npm package publishing

### ISSUE THREAD

**Issue by AdamChrimes** [nhsuk/nhsuk-frontend#197]
For our npm package publishing we need to streamline a couple of things:

- Don't publish the `/dist` folder within the npm package
- Published a minified `nhsuk.min.css` and `nhsuk.min.js` into `packages/` (without the version numbers appended to them)
- Include a versioned `jquery-0.0.0.min.js` file in there so people can just include it directly from the packages folder along with the `nhsuk.min.js`

So when installed via npm the folder structure should look something along of the lines of the screenshot below in their `node_modules` folder.

<img width="464" alt="screenshot 2018-11-13 at 14 25 00" src="https://user-images.githubusercontent.com/11615501/48419490-fdb91d00-e74f-11e8-8844-368219758bce.png">

This way people can use the same folder `packages/` for the required JavaScript and assets using the following configuration

`app.use('/nhsuk-frontend', express.static(path.join(__dirname, '/node_modules/nhsuk-frontend/packages')));`

```html
<script src="/nhsuk-frontend/nhsuk.min.js" defer></script>
<script src="/nhsuk-frontend/jquery-3.3.1.min.js"></script>

<link rel="apple-touch-icon" href="/nhsuk-frontend/assets/favicons/apple-touch-icon.png">
<link rel="icon" sizes="32x32" type="image/png" href="/nhsuk-frontend/assets/favicons/favicon.png">
```

**Comment by mikemonteith** [comment]
Problem with this code:
```
app.use('/nhsuk-frontend', express.static(path.join(__dirname, '/node_modules/nhsuk-frontend/packages')));
```
Is that the entire contents of packages will be exposed to the web, which is probably not something people want to happen unexpectedly.
e.g http://example.com/nhsuk-frontend/packages/core/README.md would serve the readme file.

---

Our root problem is that we want people to be able to serve packages/assets/* _and_ dist/* without needing two separate configs.

Maybe we should be copying assets/* into dist/ instead?

**Comment by mikemonteith** [comment]
Let's get the javascript bundles working asap and then just remove the compiled files from the npm package entirely.
