### ISSUE TITLE
Header macro should allow you to set the aria-label

### ISSUE THREAD

**Issue by GrilloPress** [nhsuk/nhsuk-frontend#288]
Currently using the header macro (from `packages/components/header/template.njk`)you get the default NHS website aria label and cannot change it. 

The label overrides the content you locally set meaning that on a service using this macro, assisted tech users would get "NHS homepage" announced  instead of whatever override I wish to set (service name etc.)

![image](https://user-images.githubusercontent.com/5756226/49797363-19a3e480-fd37-11e8-8f06-5a483789cd9e.png)

The aria-label is on line 4 of `packages/components/header/template.njk`

Possibly could default to NHS website unless given a specified override, or maybe a service name

**Comment by mcheung-nhs** [comment]
Fair point @GrilloPress - we'll look at making the aria-label an argument that can be overridden, with 'NHS homepage' as the default.

**Comment by mcheung-nhs** [comment]
@GrilloPress - Functionality available in the latest release:
https://github.com/nhsuk/nhsuk-frontend/releases/tag/0.5.3
