### ISSUE TITLE
Replace mention of care card in contents-list README.md

### ISSUE THREAD

**Issue by GrilloPress** [nhsuk/nhsuk-frontend#290]
**Documentation changes**

In `packages/components/contents-list/README.md` the third line (first paragraph) mentions the care card component.

Should be:

> Find out more about the contents list component and when to use it in the [NHS Digital service manual](https://beta.nhs.uk/service-manual/patterns/).

**Comment by mcheung-nhs** [comment]
Has been dealt with here:
https://github.com/nhsuk/nhsuk-frontend/commit/df6b5eb7e20104e31ec350703be3697e39417712
and will be updated in the next release.

**Comment by AdamChrimes** [comment]
This has been resolved in https://github.com/nhsuk/nhsuk-frontend/pull/287
