### ISSUE TITLE
Override browser styling for <address> element

### ISSUE THREAD

**Issue by GrilloPress** [nhsuk/nhsuk-frontend#291]
Currently if you use the `<address>` element you get the default browser styling. Which is italics in most browsers.

 Chrome:

![image](https://user-images.githubusercontent.com/5756226/49798882-4a861880-fd3b-11e8-8722-d69c3caa4821.png)

Firefox:

![image](https://user-images.githubusercontent.com/5756226/49798979-a2248400-fd3b-11e8-99da-08715abd60b4.png)

**Comment by mcheung-nhs** [comment]
Thanks @GrilloPress - we'll add the `<address>` styling to our core styles somewhere

**Comment by mcheung-nhs** [comment]
@GrilloPress - Default styling added to core and available in the latest release (https://github.com/nhsuk/nhsuk-frontend/releases/tag/0.5.2) so closing issue.
