### ISSUE TITLE
Add options for <a> and <input> elements on the button nunjucks template

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-frontend#296]
The current button nunjucks template only allows you to use the `<button>` element.

https://github.com/nhsuk/nhsuk-frontend/blob/master/packages/components/button/macro.njk

The button component template needs include options to use a `<a>` or `<input>` element.

**Comment by AdamChrimes** [comment]
Fixed in https://github.com/nhsuk/nhsuk-frontend/pull/324
