### ISSUE TITLE
Remove the jQuery dependency requirement

### ISSUE THREAD

**Issue by AdamChrimes** [nhsuk/nhsuk-frontend#320]
The Header component search autocomplete uses [Typeahead](https://github.com/nhsuk/typeahead.js) which requires jQuery, this has been used on the live NHS.UK website for a while. This is the only component within the Frontend library that requires jQuery, and we want to move away from using jQuery, mainly for performance improvements by not having to load in a (large) third party library.

Research and development has started into using the [GOV.UK accessible autocomplete](https://github.com/alphagov/accessible-autocomplete) so that we can remove the Typeahead script.

**Comment by mcheung-nhs** [comment]
New autocomplete (minus jQuery) merged in here:
[PR 342](https://github.com/nhsuk/nhsuk-frontend/pull/342)
so closing this issue.
