### ISSUE TITLE
Document caller method inside fieldset

### ISSUE THREAD

**Issue by GrilloPress** [nhsuk/nhsuk-frontend#385]
Like the fieldset component in the GDS frontend, the NHSUK-frontend fieldset component can use the [call block](https://mozilla.github.io/nunjucks/templating.html#call) to allow input fields to be added inside the fieldset.

This is undocumented but useful.

I had to dig around the component macro to find out this was possible.

Provide an example in the fieldset documentation [like the GDS frontend](https://design-system.service.gov.uk/components/fieldset/)

**Comment by mcheung-nhs** [comment]
@GrilloPress - documentation has been updated as requested!
Thanks.
