### ISSUE TITLE
Issue with NHS.UK Homepage header (relating to the hero component)

### ISSUE THREAD

**Issue by lmortimer99** [nhsuk/nhsuk-frontend#400]
Spotted this issue in the lab - using Firefox, zooming in 300x or 400x and applying some additional text spacing (to simulate fonts used by some dyslexic users).

It created an overlapping issue in the header.

![image001](https://user-images.githubusercontent.com/46002162/53170066-046cf100-35d7-11e9-9f86-cf1e82f1b3d8.png)
 
The easiest way (assuming you don’t have CSP on the server) is a bookmarklet:
https://www.html5accessibility.com/tests/tsbookmarklet.html
 
If that doesn’t work, or you want to keep that styling applied is to use the Stylus pluggin:
https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne?hl=en
https://addons.mozilla.org/en-US/firefox/addon/styl-us/
 
With the following CSS added:
* {
    line-height: 1.5 !important;
    letter-spacing: 0.12em !important;
    word-spacing: 0.16em !important;
}
p {
    margin-bottom: 2em;
}
  
Interestingly (or annoyingly from the team’s point of view) it depends how the over-ride is done.
 
With the bookmarklet:
![image001a](https://user-images.githubusercontent.com/46002162/53170230-878e4700-35d7-11e9-91c0-62871c47304d.png)

 
With the pluggin:
![image002a](https://user-images.githubusercontent.com/46002162/53170241-9117af00-35d7-11e9-8022-03ca2840f4e4.png)

 
I think it is because the bookmarklet is slightly better at over-riding the site’s CSS, so the line-height is being applied properly.

**Comment by AdamChrimes** [comment]
This has been fixed and released in version 2.0.0 of nhsuk-frontend.
