### ISSUE TITLE
Refactor our JavaScript using ES6 class based JavaScript

### ISSUE THREAD

**Issue by AdamChrimes** [nhsuk/nhsuk-frontend#408]
Example: https://github.com/nhsuk/nhsuk-frontend/pull/403
Related issue: https://github.com/nhsuk/nhsuk-frontend/issues/398

Description: Our JavaScript was having issues with Angular projects, and isn't the best JavaScript going. So we're going to have a look at refactoring our JavaScript using the ES6 class based approach.

A work in progress pull request has been started to investigate how we could do this: https://github.com/nhsuk/nhsuk-frontend/pull/403

This issue will have more detail added when we've investigated it a little further.

Further reading: https://scotch.io/tutorials/demystifying-es6-classes-and-prototypal-inheritance

**Comment by sabi98** [comment]
We should also think about adding an id parameter to the button template. Currently, you can only pass through type and name.

**Comment by AdamChrimes** [comment]
This was released in [3.0.0](https://github.com/nhsuk/nhsuk-frontend/blob/master/CHANGELOG.md#300---7-november-2019)
