### ISSUE TITLE
The README.md should have a nice screenshot illustrating some of the features of the UI toolkit

### ISSUE THREAD

**Issue by pacharanero** [nhsuk/nhsuk-frontend#426]
# Feature Request

## What is the issue?
The README.md should have a nice screenshot illustrating some of the features of the UI toolkit
This would help with showcasing the capability of the frontend tools

**Comment by AdamChrimes** [comment]
We're planning on providing a list of examples somewhere, both from NHS digital and the wider community. We're just collating a list now and will add them to the repo somewhere.

**Comment by pacharanero** [comment]
'The first bite is with the eyes'

Screenshot on the front of the repo or you are losing potential users right away
