### ISSUE TITLE
Hero image with image and content, longer words escaping container

### ISSUE THREAD

**Issue by AdamChrimes** [nhsuk/nhsuk-frontend#432]
When on a smaller mobile device with text enlarged, longer words escape the blue container.

Screenshot: 
![Screenshot_2019-04-03-12-10-38](https://user-images.githubusercontent.com/11615501/55504501-e4563600-5648-11e9-93f4-c8d2e62b8288.png)

A potential fix could be to make the blue container fill the full-screen width on mobile devices. However, this will need to be tested further

Screenshot:
![Screenshot_2019-04-03-15-16-51](https://user-images.githubusercontent.com/11615501/55504546-fd5ee700-5648-11e9-8c06-061a139891c8.png)

**Comment by mcheung-nhs** [comment]
I'd be happy with this. However, it would then ask the question what's the point of the background image if it's mostly hidden?

**Comment by deanc** [comment]
You might want to consider using the CSS `overflow-wrap: break-word;` property too. Support isn't too bad:
https://caniuse.com/#feat=wordwrap

**Comment by AdamChrimes** [comment]
This was released in [3.0.0](https://github.com/nhsuk/nhsuk-frontend/blob/master/CHANGELOG.md#300---7-november-2019)
