### ISSUE TITLE
Pagination padding / spacing issue on hover

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-frontend#448]
# Bug Report

## What is the issue?

On the pagination component, when you hover over the next link, the box-shadow covers the text on the previous link (if the link is particularly long).

<img width="697" alt="Screenshot 2019-05-20 at 13 48 20" src="https://user-images.githubusercontent.com/14331000/58023090-d8460b00-7b06-11e9-86ba-aa79d3ea51e6.png">

<img width="697" alt="Screenshot 2019-05-20 at 13 48 29" src="https://user-images.githubusercontent.com/14331000/58023097-db40fb80-7b06-11e9-8b28-0fcdf014c608.png">

Potential fix:

.nhsuk-pagination__link--prev {
  padding-right: nhsuk-spacing(3);
}

.nhsuk-pagination__link--next {
  padding-left: nhsuk-spacing(3);
}

**Comment by AdamChrimes** [comment]
This will be fixed as a result to changes to the focus and hover styles in https://github.com/nhsuk/nhsuk-frontend/issues/473
