### ISSUE TITLE
Promo 'mute' style variant

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-frontend#449]
A variant of a promo is used on the NHS website (https://www.nhs.uk/about-us/) which has its own bespoke CSS.

<img width="697" alt="Screenshot 2019-05-21 at 14 06 00" src="https://user-images.githubusercontent.com/14331000/58107164-3810e480-7be1-11e9-819d-7d38f6f47a3d.png">

The codebase could be reduced by making it a variant of the NHS.UK frontend promo.

A live example (prototype) of the code:
http://wagtail-frontend-test.herokuapp.com/pages/general/general_content_index

User: operation
Password: tweetybird

**Comment by AdamChrimes** [comment]
Solution used on NHS.UK:

```
.nhsuk-promo--mute {
  .nhsuk-promo__link-wrapper {
    background-color: transparent;
    box-shadow: none;

    &:hover,
    &:focus {
      background-color: transparent;
      box-shadow: none;
      outline: nhsuk-spacing(1) solid $nhsuk-focus-color;
      outline-offset: nhsuk-spacing(1) + nhsuk-spacing(2);
    }

    .nhsuk-promo__content {
        padding: nhsuk-spacing(0);
    }
  }
}
```

**Comment by AdamChrimes** [comment]
Closing this issue as we're currently doing some work with merging the Promo and Panel components.
