### ISSUE TITLE
Blue on white logo in header

### ISSUE THREAD

**Issue by danfascia** [nhsuk/nhsuk-frontend#454]
A logo of NHS Trusts and nearly all Partnerships depend on a default of a white background for their identity. This mostly stems from the use of print media I think.

Whilst I like the NHS blue header, I associate it directly with NHS England and associated bodies whereas I associate Trusts with blue on white.

Trusts often have other brand assets which they need to include on a website, again nearly always based off a white background.

I think a header variant to accept this inevitable truth would be a good idea for the toolkit (more akin to that previously available in this older toolkit https://nhsuk.github.io/frontend-library/)

**Comment by AdamChrimes** [comment]
Hi @danfascia there is already a GitHub issue covering this: https://github.com/nhsuk/nhsuk-frontend/issues/446

Going to move this comment to there and close this issue.
