### ISSUE TITLE
White on grey5 plays havoc with Windows gamma settings

### ISSUE THREAD

**Issue by danfascia** [nhsuk/nhsuk-frontend#456]
The designs depend on a rather subtle tonal gradation between nhs-white and nhs-grey5 which is very clear on a Mac screen gamma but is completely indiscernible on Windows base gamma and sRGB settings.

This means that some components such as the promo and panel do not render well on windows because it is not clear that they are a panelled structure.

I've tried this on a number of Windows 10 systems all in NHS hospitals running both Chrome and Edge

**Comment by AdamChrimes** [comment]
Hi @danfascia we've discussed this with the team and decided its not an issue at the minute as it doesn't affect usability.

- We've not had any issues when user testing the Promo component with users with access needs,
- The text colours are meeting the AA colour contrast ratio,
- If we changed the grey background colour, it would have a massive impact across everything else.

We'll keep an eye on it in the usability testing and see if anyone else faces issues.
