### ISSUE TITLE
Reponsive menu close [ X ] icon needs cursor: hand hover state

### ISSUE THREAD

**Issue by danfascia** [nhsuk/nhsuk-frontend#457]
On the responsive menu, the [ X ] icon needs a `cursor: hand ` adding to it on hover state.

**Comment by mcheung-nhs** [comment]
Hi @danfascia,
Could you tell me what os/browser version you are using?
I've looked at the header menu [x] on recent versions of Safari, Chrome, Firefox and Edge and I get the pointer graphic when hovering.
Thanks.

**Comment by danfascia** [comment]
Chrome 74 on OSX 10.13.6

It's a small detail since most people shouldn't see a cursor: hand because it's a mobile only menu mostly for touch devices... but it's the kind of thing that bugs front end devs too !

**Comment by AdamChrimes** [comment]
Hi @danfascia 

I've also checked this on Chrome Version 75.0.3770.100, Safari, and FireFox and get the pointer graphic when hover.
