### ISSUE TITLE
Increase reading width

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-frontend#462]
**Problem**

When the base font size changed from 19px to 16px, the `nhsuk-u-reading-width` utility class became smaller.

Live site - 37em, base font size 19px:

![Screenshot 2019-06-10 at 12 03 25](https://user-images.githubusercontent.com/14331000/59194185-1cfe1880-8b80-11e9-9516-56a5a121a260.png)

Frontend - 37em, base font size 16px:

![Screenshot 2019-06-10 at 12 03 59](https://user-images.githubusercontent.com/14331000/59194194-212a3600-8b80-11e9-8e2c-e44a80496e05.png)

Frontend - 44em, base font size 16px :

![Screenshot 2019-06-10 at 12 04 14](https://user-images.githubusercontent.com/14331000/59194206-2f785200-8b80-11e9-8c07-69530cc2d563.png)

**Solution:**

Increase reading width value from 37em to 44em.

```
.nhsuk-u-reading-width {
  max-width: 44em;
}
```

**Comment by AdamChrimes** [comment]
Fixed in 2.2.0
