### ISSUE TITLE
Text colour utility classes

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-frontend#465]
The NHS website uses text colour utility classes.

For example:

To utilise the secondary text colour, `nhsuk-u-secondary-text-color` was created.

```
.nhsuk-u-secondary-text-color {
  color: $nhsuk-secondary-text-color !important;
}
```

`<p class="nhsuk-u-secondary-text-color">Published on: 15 March 2018</p>`

This could be a useful addition to the frontend library.

**Comment by AdamChrimes** [comment]
Fixed in v2.3.0.
