### ISSUE TITLE
Make the BackstopJS tests shareable and possibly change reference to live URL

### ISSUE THREAD

**Issue by AdamChrimes** [nhsuk/nhsuk-frontend#471]
This is more of an early discussion than a suggestion or a bug...

There are various language-specific ports of the NHS.UK frontend library in development - it would be good if these ports could use the same test suite and reference screenshots as we do on the frontend library to ensure high quality and consistency. 

- We could have the BackstopJS tests configuration and reference screenshots produced within the npm package then users can point their BackstopJS to this configuration. The references and configuration would need to be versioned to match the version of the npm package.
- We could potentially use the GitHub hosted pages as the reference URL, instead of having 300 image files hosted in the repo/npm package (however this would require some changes to our pipeline).
- Tests could be in each of the individual components could be split out of the massive `backstop.js` configuration file into their own individual files.  eg. `action-link.spec.js`. This would make it modular, similar to the Scss, and could be selectively run or imported.

Discussions are ongoing with the NHS.UK test team and teams creating ports of the NHS.UK frontend.

**Comment by Tomdango** [comment]
A relatively "plug and play" solution would be the use of [Git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules). This would mean you can pull the backstop assets away into it's own repository, then clone it as a submodule inside the nhsuk-frontend repository. This way we can clone the assets into our own repositories and use them right away.

**Comment by AdamChrimes** [comment]
I don't think there has been enough interest in this to take forward.
