### ISSUE TITLE
Lede (intro) text

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-frontend#474]
Lede text style needs adding to the nhsuk-frontend.

See the issue on the [nhsuk service manual backlog](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/106).

The code can be found in the NHS.UK wagtail repo.

**Comment by AdamChrimes** [comment]
Here's the code for Lede text on the NHS digital service manual: https://github.com/nhsuk/nhsuk-service-manual/blob/develop/app/styles/main.scss#L22

**Comment by AdamChrimes** [comment]
Fixed in v2.3.0.
