### ISSUE TITLE
Backstop test for Bold Label uses the wrong url and reference images

### ISSUE THREAD

**Issue by xLasercut** [nhsuk/nhsuk-frontend#481]
# Bug Report

## What is the issue?

```js
{
  "label": "Label",
  "url": `${TEST_HOST}/components/label/index.html`
 },
{
  "label": "Label with bold text",
  "url": `${TEST_HOST}/components/label/index.html`
}
```

bold text test should use `http://localhost:3000/components/label/bold.html` 
The tests pass because reference images for bold label are the same as those of regular label

**Comment by AdamChrimes** [comment]
Fixed in 2.2.1
