### ISSUE TITLE
Missing Nunjuck example for second image in README

### ISSUE THREAD

**Issue by nnekaO** [nhsuk/nhsuk-frontend#483]
README has no nunjuck macro for the example with no caption https://github.com/nhsuk/nhsuk-frontend/tree/master/packages/components/images#nunjucks-macro

**Comment by AdamChrimes** [comment]
Hi @nnekaO 

Thanks for raising this issue, is this something you could give a go at fixing and contributing back?

It will be the same macro just without the "caption" field.

**Comment by nnekaO** [comment]
I'd love to, just need to figure out how to contribute back.
