### ISSUE TITLE
Header: Autocomplete dropdown

### ISSUE THREAD

**Issue by sabi98** [nhsuk/nhsuk-frontend#484]
# Bug Report

## What is the issue?
The autocomplete dropdown moves as you scroll down.

## What steps are required to reproduce the issue?

Go on NHS.uk and type headache and scroll down whilst the dropdown is open.

## Is there anything else you think would be useful in recreating the issue?

![image](https://user-images.githubusercontent.com/43380323/60277700-f963fd80-98f5-11e9-9e10-4c776a4b175d.png)

**Comment by AdamChrimes** [comment]
You going to give this fix ago @sabi98?

**Comment by AdamChrimes** [comment]
This has been released in v2.3.1.
