### ISSUE TITLE
Allow override for copyright in footer macro

### ISSUE THREAD

**Issue by GrilloPress** [nhsuk/nhsuk-frontend#485]
Reviewing some work with @samanthasaw and we noticed you couldn't override the copyright notice in the footer macro.

Not every service will be crown copyright. Either at all, or may have more complicated copyright issues.

Probably should be able to either toggle the visibility and use a different copyright

**Comment by AdamChrimes** [comment]
Hi @GrilloPress and @samanthasaw 

Thanks for raising this issue - as you know the team is abit smaller than it used to be and have other commitments (along with a growing issues list). 

Is this something you could potentially give a go and open a pull request with the proposed changes?

**Comment by GrilloPress** [comment]
Will do. I've just had a look at the macro and think I could do it.

I'll set up a branch for review

**Comment by AdamChrimes** [comment]
@GrilloPress something like this would probably do the trick:

template.njk

`<p class="nhsuk-footer__copyright">{% if params.copyright %}{{ params.copyright }}{% else %}&copy; Crown copyright{% endif %}</p>`

then the macro would be:

{{ footer({
  "links": [
    {
      "URL": "https://www.nhs.uk/nhs-sites/",
      "label": "NHS sites"
    },
    {
      "URL": "https://www.nhs.uk/about-us/",
      "label": "About us"
    },
    {
      "URL": "https://www.nhs.uk/contact-us/",
      "label": "Contact us"
    },
    {
      "URL": "https://www.nhs.uk/about-us/sitemap/",
      "label": "Sitemap"
    },
    {
      "URL": "https://www.nhs.uk/our-policies/",
      "label": "Our policies"
    }
  ],
 "copyright": "Custom copyright text"
})}}

**Comment by GrilloPress** [comment]
Yeah that's pretty much what I'm thinking. Just need to sit down and do it.

Would we want to escape the text just in case? or provide an html or text switch?

**Comment by AdamChrimes** [comment]
HTML could be used but that means people could put anything in there (eg. Care cards), we may want to stick to just text as any custom HTML probably would fit in the there anyway.

**Comment by AdamChrimes** [comment]
This is done just waiting for next release.

**Comment by AdamChrimes** [comment]
This has been released in v2.3.1. 

Thanks @GrilloPress for raising the issue.
