### ISSUE TITLE
Expanders should be consistant on supported browsers (Edge)

### ISSUE THREAD

**Issue by Ross-Clark** [nhsuk/nhsuk-frontend#508]
# Bug Report

## What is the issue?

When you view the expander component on microsoft edge, the plus icon on the expander is not consistent with other browsers. The plus icon is larger in edge and it has less spacing to the text

## What steps are required to reproduce the issue?

1) Open Edge
2) Navigate to  https://github.com/nhsuk/wagtail-nhsuk-frontend/blob/master/wagtailnhsukfrontend/templates/wagtailnhsukfrontend/expander_group.html

## What was the environment where this issue occurred?

* Device: ThinkPad p51
* Operating System: Windows 10
* Browser: Edge
* Browser version: 44.17763.1.0
* NHS.UK frontend package version: Latest

## Is there anything else you think would be useful in recreating the issue?

[Link to expander](https://github.com/nhsuk/wagtail-nhsuk-frontend/blob/master/wagtailnhsukfrontend/templates/wagtailnhsukfrontend/expander_group.html)

**Comment by Ross-Clark** [comment]
![Expander+](https://user-images.githubusercontent.com/43380330/61782513-0fce7d80-adfe-11e9-8a13-18f337281676.png)

**Comment by AdamChrimes** [comment]
Managed to replicate on Browserstack. 

Visually it looks like the the +/- icons are bigger on Microsoft Edge. So I think Edge struggles with the way we've done the background image for the +/i icons (particularly the `width='32'` part - where we set the sizing of the icon)

`background: url("data:image/svg+xml,%3Csvg class='nhsuk-icon nhsuk-icon__plus' xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' width='32' aria-hidden='true'%3E%3Ccircle cx='12' cy='12' r='10' fill='%23005eb8'%3E%3C/circle%3E%3Cpath fill='none' stroke='%23fff' stroke-linecap='round' stroke-miterlimit='10' stroke-width='2' d='M12 8v8M8 12h8'%3E%3C/path%3E%3C/svg%3E%0A") left -2px center no-repeat;`

Removing the `width='32'` and adding a new rule CSS `background-size: 32px;` seems to fix it. I'll test it further.

<img width="541" alt="Screenshot 2019-07-24 at 13 20 05" src="https://user-images.githubusercontent.com/11615501/61792935-c853eb80-ae15-11e9-8e10-05d7ee1659a2.png">

**Comment by AdamChrimes** [comment]
This is done just waiting for next release

**Comment by AdamChrimes** [comment]
This has been released in v2.3.1
