### ISSUE TITLE
Header search query doesn't submit with enter key.

### ISSUE THREAD

**Issue by sabi98** [nhsuk/nhsuk-frontend#522]
## What is the issue?
Pressing enter after entering a search term doesn't do anything. 

Pressing Return should give results from both search bars (main search bar and search results page), currently only clicking the magnifying glass icon returns results.

This is not helpful for keyboard accessibility and we observed many users hitting Return and no action taking place.

**Comment by AdamChrimes** [comment]
This will be released in v2.3.1

**Comment by AdamChrimes** [comment]
This has been released in v2.3.1.

Thanks @sabi98 for fixing!
