### ISSUE TITLE
Header search results dropdown doesn't disappear when you scroll down the page.

### ISSUE THREAD

**Issue by sabi98** [nhsuk/nhsuk-frontend#525]
# Bug Report

## What is the issue?

When scrolling down with search results dropdown the expected behaviour is that it should disappear. However, this doesn't happen and it stays open regardless of how much you scroll. Only disappears by clicking.

## What was the environment where this issue occurred?

* Device:
* Operating System:
* Browser:
* Browser version:
* NHS.UK frontend package version:
* Node version:
* npm version:

**Comment by AdamChrimes** [comment]
Spoke to @sabi98 and we've decided that is a non-issue, the behavior should be left as it is to avoid causing complications on different devices/assistive technology.
