### ISSUE TITLE
Inconsistant spacing between date input fields

### ISSUE THREAD

**Issue by J1883R15H** [nhsuk/nhsuk-frontend#529]
# Bug Report
A manual tester noticed the spacing between day and month fields is slightly smaller than the spacing between month and year, due to the month label being larger than the field itself, effecting the look and feel of our product.

![image](https://user-images.githubusercontent.com/44647192/65045169-3c15fe80-d956-11e9-9cf9-7db995fa6b7c.png)

## What was the environment where this issue occurred?

* Device:
* Operating System:
* Browser:
* Browser version:
* NHS.UK frontend package version:
* Node version:
* npm version:

**Comment by AdamChrimes** [comment]
Hi @J1883R15H thanks for opening this issue, the team will triage this on Monday and get back to you on it.

**Comment by AdamChrimes** [comment]
This visual inconsistency also seems to be the same in the GOV.UK Frontend ([GOV.UK design system - Date input example](https://design-system.service.gov.uk/components/date-input/date-of-birth/index.html))

It could potentially be fixed by creating a new modifier class to reduce the font size of the date input label such as:

```
.nhsuk-date-input__label---xs {
  @include nhsuk-font(16);
}
``

This fixes the spacing issue however it reduces the font size by quite a bit and would require further user testing to make sure that the font size is still usable and is accessible. 

I've put a message out for design input on this.

**Comment by AdamChrimes** [comment]
Hi @J1883R15H, did you attempt the suggested fix above? How did it test with users for usability and readability?

**Comment by AdamChrimes** [comment]
Going to close this issue due to inactivity and the initial concerns in the original response. Feel free to reopen if you think it might still be an issue that needs addressing.
