### ISSUE TITLE
JavaScript error if the header search is not present 

### ISSUE THREAD

**Issue by tomdoughty** [nhsuk/nhsuk-frontend#531]
# Bug Report

## What is the issue?

A JavaScript error occurs when the header search is not present.

## What steps are required to reproduce the issue?

Run http://0.0.0.0:3000/ locally and this error will appear in the console.

## What was the environment where this issue occurred?

* Device: Apple MacBook Pro
* Operating System: macOS 10.14.6
* Browser: Google Chrome
* Browser version: 77.0.3865.90
*
* NHS.UK frontend package version: 2.3.1
* Node version: v10.16.3
* npm version: 6.9.0

## Is there anything else you think would be useful in recreating the issue?

The error given is: 
`Cannot read property 'addEventListener' of null`

**Comment by AdamChrimes** [comment]
This was fixed in [v2.3.2](https://github.com/nhsuk/nhsuk-frontend/blob/master/CHANGELOG.md#232---30th-september-2019)
