### ISSUE TITLE
JAWS and NVDA not detecting heading inside legend

### ISSUE THREAD

**Issue by Fenwick17** [nhsuk/nhsuk-frontend#534]
# Bug Report

## What is the issue?

When using an `<h#>` element within the `<legend>` as per the ['Fieldset as page heading'](https://nhsuk.github.io/nhsuk-frontend/components/fieldset/page-heading.html) pattern Jaws and NVDA will not treat this as a heading, therefore it does not display in the list of headings. 

## What steps are required to reproduce the issue?

Access any page with a `<h#>` inside a `<legend>` with Jaws or NVDA

## What was the environment where this issue occurred?

* Device: Laptop
* Operating System: Windows 10
* Browser: Chrome
* Browser version: Latest
* NHS.UK frontend package version: 2.3.1

**Comment by Ross-Clark** [comment]
I cant replicate this issue with my set up
would like to go through this with you when possible

**Comment by nickcolley** [comment]
Hey folks,

I think we've been made aware of the same issue and will be tackling this in this issue on GOV.UK Frontend: https://github.com/alphagov/govuk-frontend/issues/1605

**Comment by AdamChrimes** [comment]
Thanks @nickcolley, @Fenwick17 found it to the be the `overflow: hidden;` on the fieldset which was causing the problem for us (https://github.com/nhsuk/nhsuk-frontend/pull/542). 

When Adam was testing this, he also tested GOVUK frontend and found it not to be an issue with the GOVUK fieldset. It looks like this particular fix was made to the GOVUK fieldset back in September (https://github.com/alphagov/govuk-frontend/pull/1548).

So I'm not sure if this is a different issue but I'll leave this open for discussion and maybe we can help, Adam may be able to add more info to this.

**Comment by AdamChrimes** [comment]
We've fixed the original issue raised in release 3.0.0. 

Related: https://github.com/alphagov/govuk-frontend/issues/1605#issuecomment-545484044

I'll close this issue for now.
