### ISSUE TITLE
Use the latest version of GOV.UK accessible autocomplete

### ISSUE THREAD

**Issue by AdamChrimes** [nhsuk/nhsuk-frontend#545]
We use the [GOV.UK accessible autocomplete](https://github.com/alphagov/accessible-autocomplete) via npm for our autocomplete functionality. There was recently a new breaking change version released, fixing accessibility issues, [see GOV.UK accessible autocomplete releases page for more details about the release](https://github.com/alphagov/accessible-autocomplete/releases).

We should look to update our version to use the latest version (2.0.1). Usually it would just be a simple version bump, however due to it being a breaking change and because we have custom functionality and styles on top, we need to make sure that nothings breaks on our end (visual, functionality or accessibility). So will need abit of testing.

**Comment by tomdoughty** [comment]
If anybody picks this up before me give me a shout as I have decoupled our autocomplete usage from the header search as part of the ES6 refactor. It would be worth merging that in with this.

**Comment by AdamChrimes** [comment]
This was released in [3.0.0](https://github.com/nhsuk/nhsuk-frontend/blob/master/CHANGELOG.md#300---7-november-2019)
