### ISSUE TITLE
Package won't install with Node LTS version

### ISSUE THREAD

**Issue by tomdoughty** [nhsuk/nhsuk-frontend#547]
# Bug Report

## What is the issue?

As of 21/10/2019 [Node.js LTS version is 12.x.](https://nodejs.org/en/about/releases/) current package lock has our version of node-sass which is used by gulp-sass locked to an incompatible version.

## What steps are required to reproduce the issue?

Clone the repo
Using Node.js 12.13.0 run `npm install`
Installation fails due to incompatible node-sass with Node v12.x

## What was the environment where this issue occurred?

* NHS.UK frontend package version: 2.3.2
* Node version: v12.13.0
* npm version: 6.12.0

**Comment by AdamChrimes** [comment]
This has been fixed in https://github.com/nhsuk/nhsuk-frontend/pull/548

Thanks for raising and fixing @tomdoughty ⭐️
