### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-frontend#56]
Use this issue to refactor the component: **Footer**

## Refactor checklist

- [x] Sass file contains comments, using the comments template format
- [x] Refactor code using BEM for naming
- [x] Remove / refactor any code smells
- [x] Remove / refactor any 'random numbers' or make comments where it is necessary to use

## Component checklist

- [x] SCSS
- [x] SCSS lint
- [x] HTML template
- [x] HTML validate & lint
- [x] Nunjucks macro
- [x] A standalone example
- [x] README/Documentation
- [x] Pseudocode tests
- [x] Visual tests 
- [x] Tested against our [testing policy](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/testing.md) (Resolution, Browser & Accessibility)
- [x] Print stylesheet considered
- [x] CHANGELOG

**Comment by AdamChrimes** [comment]
HTML validating, SVG issues:

- Attribute src not allowed on element image at this point.
- Element image is missing required attribute height.
- Element image is missing required attribute width.
