### ISSUE TITLE
Displaying alt attributes affects formatting

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-frontend#570]
# Bug Report

## What is the issue?

Looking at the forms guidance, filter question page:
https://beta.nhs.uk/service-manual/content/how-to-write-good-questions-for-forms/use-filter-questions-to-route-users

The radios examples lose their circles and formatting slips when I switch on view alt attributes. Examples attached.

![Screenshot 2019-11-26 at 09 32 39](https://user-images.githubusercontent.com/45792959/69618551-fcdceb80-1031-11ea-903e-bc8266d6ebe3.png)

![Screenshot 2019-11-26 at 09 33 38](https://user-images.githubusercontent.com/45792959/69618582-05cdbd00-1032-11ea-8677-260c4a73b7ee.png)

![Screenshot 2019-11-26 at 09 34 11](https://user-images.githubusercontent.com/45792959/69618597-0e25f800-1032-11ea-953f-021374ed16f2.png)

## What steps are required to reproduce the issue?

I'm using Chrome with a web developer extension. When I click on view alt attributes, it affects the way the radio examples display.

![Screenshot 2019-11-26 at 09 36 41](https://user-images.githubusercontent.com/45792959/69618630-1aaa5080-1032-11ea-928d-bef21891dcc8.png)

## What was the environment where this issue occurred?

* Device: Mac
* Operating System: iOS
* Browser: Google Chrome
* Browser version: 78.0.3904.108 (Official Build) (64-bit)

## Is there anything else you think would be useful in recreating the issue?

Please let me know if you need any more info.

**Comment by AdamChrimes** [comment]
Hi @sarawilcox after triaging this, I'm not sure this is an issue with NHS.UK frontend, it happens as a result of using the web developer extension to debug pages and wouldn't happen in a non development scenario. I use the same web developer extension on Chrome and after toggling a few of the options, web pages do start to look a bit strange.

**Comment by sarawilcox** [comment]
OK, thanks @AdamChrimes. Good to know.
