### ISSUE TITLE
Add structured data for coronavirus-covid-19 page

### ISSUE THREAD

**Issue by Nooshu** [nhsuk/nhsuk-frontend#599]
I'd imagine this is the incorrect repository to be logging this against, but can hopefully be moved / logged where needed then closed.

Last week Google [added the ability](https://developers.google.com/search/docs/data-types/special-announcements) to tell search engines specifically about COVID-19 guidance and information using structured data. Properties for the `SpecialAnnouncement` can be [found here](https://developers.google.com/search/docs/data-types/special-announcements#data-type-definitions). I've created a mock-up below of what this structured data could look like based off the [work that the GOV.UK team did last week](https://search.google.com/structured-data/testing-tool?utm_campaign=devsite&utm_medium=jsonld&utm_source=special-announcement#url=https%3A%2F%2Fwww.gov.uk%2Fcoronavirus).

```
<script type="application/ld+json">
{
   "@context":"http://schema.org",
   "@type":"SpecialAnnouncement",
   "mainEntityOfPage":{
      "@type":"WebPage",
      "@id":"https://www.nhs.uk/conditions/coronavirus-covid-19"
   },
   "name":"Coronavirus (COVID-19): Advice for everyone",
   "datePublished":"2020-04-03T14:29:42.000+00:00",
   "dateModified":"2020-04-03T16:57:50.000+00:00",
   "text":"NHS advice about coronavirus (COVID-19), including what to do if you think you have it and how to reduce your chances of getting it.",
   "author":{
      "@type":"Organization",
      "email":"nhswebsite.servicedesk@nhs.net",
      "logo":"https://www.nhs.uk/nhscwebservices/documents/logo1.jpg",
      "name":"NHS website",
      "url":"https://www.nhs.uk"
   },
   "image":null,
   "category":"https://www.wikidata.org/wiki/Q81068910",
   "datePosted":"2020-04-03T14:29:42.000+00:00",
   "diseasePreventionInfo":"https://www.nhs.uk/conditions/coronavirus-covid-19",
   "diseaseSpreadStatistics":"https://www.gov.uk/government/publications/covid-19-track-coronavirus-cases",
   "newsUpdatesAndGuidelines":"https://www.nhs.uk/conditions/coronavirus-covid-19",
   "publicTransportClosuresInfo":"https://www.gov.uk/guidance/coronavirus-covid-19-uk-transport-and-travel-advice",
   "quarantineGuidelines":"https://www.nhs.uk/conditions/coronavirus-covid-19/self-isolation-advice",
   "schoolClosuresInfo":"https://www.gov.uk/check-school-closure",
   "travelBans":"https://www.gov.uk/guidance/travel-advice-novel-coronavirus"
}
</script>
```

There is a mixture of NHS urls and GOV.UK urls since not all specific guidance is published on the NHS website. But this cross-linking between sites should be helpful for users / Google. 

Output from the [structured dating testing tool](https://search.google.com/structured-data/testing-tool) looks like this:

![NHS Structured data on COVID-19 page example](https://user-images.githubusercontent.com/1223960/78462760-0b689d00-76cd-11ea-906e-1d47340442e6.png)

**Comment by AdamChrimes** [comment]
Hey @Nooshu thanks for raising this, I'll forward it onto the teams that have been working on content modularisation for Google and see what they think.

**Comment by jameslumgair** [comment]
Hey @Nooshu, thanks for this. We are using the [HealthTopicContent](https://schema.org/HealthTopicContent) schema to provide search engines with modularised content: [Google](https://g.co/kgs/rXN6jN) and [Bing](https://www.bing.com/search?q=coronavirus). Although the `SpecialAnnouncement` schema could also be used it is unlikely our content really matches the announcement style at the moment (regular messages which expire after a week/month). If the organisation can give regular announcements then it's ideal, especially for physical buildings and locations.

**Comment by Nooshu** [comment]
Thanks for clarifying @jameslumgair. Glad to see the content is already being indexed correctly using structured data. I will close this issue.
