### ISSUE TITLE
Hint component can render block-level elements as valid HTML

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-frontend#620]
## What

Switch the hint component wrapping element from span to div

## Why

Spans are inline elements. Meaning they shouldn’t have block elements in them, like paragraphs etc.

For most hint text uses that’s fine. But there are many examples where hint text is a couple of lines. Not one.

Also see: https://github.com/alphagov/govuk-frontend/pull/1855

**Comment by AdamChrimes** [comment]
This will be released as part of 4.0.0

**Comment by AdamChrimes** [comment]
Released
