### ISSUE TITLE
Bug on search button for NHS.UK live site

### ISSUE THREAD

**Issue by Tosin-88** [nhsuk/nhsuk-frontend#621]
# Bug Report

## What is the issue?
Search button returns an error when selected on the search results page for mobile

## What steps are required to reproduce the issue?

Go to NHS.UK ---> Select search icon ----> Type any thing in search -----> Once on results page -----> select search icon at the top again ------> ERROR

## What was the environment where this issue occurred?

* Device: iPhone XR
* Operating System: iOS 13.6
* Browser: Safari 
* Browser version: N/A
* NHS.UK frontend package version: N/A
* Node version: N/A
* npm version: N/A

## Is there anything else you think would be useful in recreating the issue?

![Image from iOS](https://user-images.githubusercontent.com/44926463/90122437-2e7b1b80-dd55-11ea-908a-7e172a3b57ab.png)

**Comment by AdamChrimes** [comment]
Hey @Tosin-88 thanks for raising this, it looks like this was an issue with the Search page implementation rather than the frontend library component. It looks like it has been fixed on the website now.
