### ISSUE TITLE
 footer design of Login page and footer design of other page are not same

### ISSUE THREAD

**Issue by kmlhsn** [nhsuk/nhsuk-frontend#625]
1.Go to https://www.nhs.uk/
2. scroll down to footer

Description:
 footer design of Login page and footer design of other page are not same

Expectation:
 footer design of Login page and footer design of other page should be same

screenshot of login page footer
![image](https://user-images.githubusercontent.com/32615215/91667500-d26f1000-eb26-11ea-8689-e8af6358b328.png)
screenshot of front page footer

![image](https://user-images.githubusercontent.com/32615215/91667504-d733c400-eb26-11ea-80f0-864b47451550.png)

**Comment by AdamChrimes** [comment]
Hey @kmlhsn 

See [my comment](https://github.com/nhsuk/nhsuk-frontend/issues/624#issuecomment-685571711) in #624
