### ISSUE TITLE
Create responsive table component

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-frontend#641]
## What 

Create responsive table component in the NHS.UK frontend.

## Why

Having agreed to add this component to the design system, we now need to build the component in Frontend ready for release.

**Comment by henocookie** [comment]
Won't re-open this issue, but I wonder if any of the advice or guidance in this article is of any value, which we don't already have covered https://adrianroselli.com/2020/11/under-engineered-responsive-tables.html
