### ISSUE TITLE
NHS logo SVG: xlink:href vs href

### ISSUE THREAD

**Issue by idiosyn** [nhsuk/nhsuk-frontend#673]
PR https://github.com/nhsuk/nhsuk-frontend/pull/657 added the `xlink` namespace to the NHS logo SVG. This was needed because the SVG code uses `xlink:href`.

But wouldn’t it be better to use `href` instead of `xlink:href` (and then, of course, remove the `xlink` namespace)?

The [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href) says this about `xlink:href`:

> **Deprecated since SVG 2**
> This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the compatibility table at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time.

And:

> **Note:** SVG 2 removed the need for the `xlink` namespace, so instead of `xlink:href` you should use [`href`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/href).

**Comment by thibaudcolas** [comment]
Despite what MDN says, `xlink:href` is supported in all browsers, while `href` doesn’t work in [older versions of Safari (12.1 and below)](https://caniuse.com/mdn-svg_elements_use_href). Considering how widespread `xlink:href` is, I doubt there will be any browser removing support for it in the foreseeable future. For SVG 2 – worthy read: https://css-tricks.com/svg-2-conundrum/.

**Comment by idiosyn** [comment]
Thanks for the links. Great point about Safari.

**Comment by AdamChrimes** [comment]
Hey @idiosyn thanks for opening this issue.

As Thibaud mentioned, we need to consider browser support for this change. 

The `xlink:href` is used for the SVG PNG fallback icon for Internet Explorer 8 and 9, we're going to be reviewing our browser support policy soon and may possibly be dropping IE8 and IE9 support. Then we can remove the fallback, which would remove the need for the `xlink:href` all together.

**Comment by mcheung-nhs** [comment]
Will be removed in release 5.0.0 as part of our deprecation of IE8-10 - https://github.com/nhsuk/nhsuk-frontend/pull/680

**Comment by AdamChrimes** [comment]
This will be fixed in release 5.0.0 (next week)

**Comment by Yogurt4** [comment]
> Despite what MDN says, `xlink:href` is supported in all browsers, ...

Just for reference, this doesn't seem to stand any longer. `href` (without namespace) works with all current browsers [not tested on Safari though, for their general dislike for SVG].

Furthermore, using `xlink:href`:

Firefox (107.0): Error page with **XML Parsing Error: prefix not bound to a namespace**
Chrome (107.0.5304.122): Error page with **Namespace prefix xlink for href on linearGradient is not defined**
Internet Explorer (22H2 OS Build 19045.2311): Blank page, with **XML5660: The specified prefix has not been declared.** on the Console.
Microsoft Edge (107.0.1418.62): Blank page, nothing on Console.

I've tried it with `<style>+<linearGradient>`, `<symbol>+<use>` and `<def>+<filter>`.
