### ISSUE TITLE
Skip to main content inconsistencies 

### ISSUE THREAD

**Issue by mikestreety** [nhsuk/nhsuk-frontend#716]
# Bug Report

## What is the issue?

There is an inconsistency between the skip link href and ID on the main content within the docs

## What steps are required to reproduce the issue?

On the [Page Template page](https://service-manual.nhs.uk/design-system/styles/page-template) the demo content has a `-` hyphen in the `href` but on the ID. This occurs in a few places in the docs

![image](https://user-images.githubusercontent.com/354085/110962620-1306dc00-8349-11eb-8aa5-6ea5471f37cb.png)

**Comment by AdamChrimes** [comment]
Hey @mikaelmetthey good spot, they should be the same throughout!

I've opened a [pull request to fix this on the NHS digital service manual repo](https://github.com/nhsuk/nhsuk-service-manual/pull/1043), will aim to get this fixed and released for Monday.

**Comment by mikestreety** [comment]
Thanks for the quick response @AdamChrimes!

**Comment by AdamChrimes** [comment]
This was released this morning https://service-manual.nhs.uk/design-system/styles/page-template

Thanks again for raising this @mikestreety
