### ISSUE TITLE
Transactional header long service names not wrapping correctly 

### ISSUE THREAD

**Issue by chrimesdev** [nhsuk/nhsuk-frontend#720]
## Description
 
Long services names on the [Header transactional with service name](https://nhsuk.github.io/nhsuk-frontend/components/header/header-transactional-service-name.html) aren't wrapping correctly on smaller mobile devices. 

There is a modifier class to fix this `nhsuk-header__transactional-service-name--long`, however the default behaviour should be that the service name always wraps below without the need for the modifier class.

We should remove the `nhsuk-header__transactional-service-name--long` modifier class and make the default behaviour wrap underneath for service names of any length. This behaviour would also match the [Header with a service name](https://nhsuk.github.io/nhsuk-frontend/components/header/header-service-name.html).

Example of the current default:

![Screenshot 2021-03-17 at 14 21 14](https://user-images.githubusercontent.com/11615501/111483661-ea0d8f00-872c-11eb-967b-332d723f48a5.png)

Example when using the modifier class (ideal default)

![Screenshot 2021-03-17 at 14 28 56](https://user-images.githubusercontent.com/11615501/111483877-20e3a500-872d-11eb-8e2b-4659e5a481a0.png)

**Comment by AdamChrimes** [comment]
Related comment https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/16#issuecomment-621918905
