### ISSUE TITLE
Implications of setting font-family on html selector

### ISSUE THREAD

**Issue by windy1** [nhsuk/nhsuk-frontend#728]
# Bug Report

## What is the issue?

Because of [how cache partitioning works in most modern browsers](https://www.zdnet.com/article/chromes-new-cache-partitioning-system-impacts-google-fonts-performance/), it's now recommended that websites self-host their fonts. Unfortunately, `nhsuk-frontend` does not make this easy to achieve. The culprit is [setting the `font-family` on an `html` selector](https://github.com/nhsuk/nhsuk-frontend/blob/master/packages/core/elements/_page.scss#L19). Even when overriding with an `!important` flag, Chrome will still attempt to load the external font because it will still be set on the original stylesheet.

I would recommend that the `font-family` not be set explicitly on the `html` selector and instead leave it to the downstream dependents to set.

## What steps are required to reproduce the issue?

1. Create an application that overrides the `font-family` in the `html` selector
2. Observe that the `nhsuk-frontend` font is still loaded

## What was the environment where this issue occurred?

* Operating System: Windows 10 Pro
* Browser: Google Chrome
* Browser version: 89
* NHS.UK frontend package version: 4.1.0
* Node version: 14.x
* ~npm~ yarn version: 1.22.10

**Comment by AdamChrimes** [comment]
Hey @windy1 thanks for opening this issue, the team will get together and have a chat about this. If you want to open a pull request with your proposed idea or solution that is something we'd be grateful for.

**Comment by windy1** [comment]
Hi @AdamChrimes, thanks for the timely response. I've submitted a PR https://github.com/nhsuk/nhsuk-frontend/pull/732

Thanks!

**Comment by andymantell** [comment]
This was fixed in #732
