### ISSUE TITLE
Expected footer image is incorrect in backstop test

### ISSUE THREAD

**Issue by xLasercut** [nhsuk/nhsuk-frontend#733]
# Bug Report

## What is the issue?

Footer page reference image is incorrect in backstop test

## What steps are required to reproduce the issue?

Run backstop test with correct footer page. Currently visiting the footer example page gives a "Cannont GET /components/footer/index.html"

## What was the environment where this issue occurred?

* Device: Any
* Operating System: Any
* Browser: Google Chrome
* Browser version: 90.0.4430.93
* NHS.UK frontend package version: 5.0.0
* Node version: v14.16.0
* npm version: 6.14.11

## Is there anything else you think would be useful in recreating the issue?

![image](https://user-images.githubusercontent.com/32720585/116272735-0e6f7900-a779-11eb-98fc-c7971596de1d.png)

**Comment by chrimesdev** [comment]
Thanks @xLasercut for some strange reason the Footer page is no longer compiling, I'll take a look.

**Comment by chrimesdev** [comment]
Thanks @xLasercut looks like the Footer preview page was accidentally deleted - I will take a look at this.
