### ISSUE TITLE
Axe/Lighthouse accessibility issue with Warning Callout component

### ISSUE THREAD

**Issue by nhsbsa-chris** [nhsuk/nhsuk-frontend#735]
# Bug Report

## What is the issue?

We are using the Warning Callout component but Axe and Lighthouse both report an issue with the use of `span[role="text"]`

**Axe**

<img width="1440" alt="Screenshot 2021-04-29 at 13 16 50" src="https://user-images.githubusercontent.com/34475600/116549505-7941c100-a8ed-11eb-907b-bc6e32b7463f.png">

**Lighthouse**

<img width="1440" alt="Screenshot 2021-04-29 at 13 18 50" src="https://user-images.githubusercontent.com/34475600/116549509-7c3cb180-a8ed-11eb-83c3-6cbb0b839c0f.png">

## What steps are required to reproduce the issue?

1. Add the following extensions to Chrome - Axe DevTools and Wave Evaluation Tool
2. Navigate to the following page - https://nhsuk.github.io/nhsuk-frontend/components/warning-callout/custom-heading.html
3. Inspect - Axe DevTools - Scan ALL of my Page - AND - Lighthouse - Accessibility/Desktop or Mobile - Generate Report

## What was the environment where this issue occurred?

* Device: MacBook Pro 
* Operating System: macOS Catalina (Version 10.15.7)
* Browser: Google Chrome
* Browser Version: 89.0.4389.128
* NHS.UK Frontend Package Version: 5.0.0
* Node Version: 10.15.1
* NPM Version: 6.4.1

**Comment by mcheung-nhs** [comment]
Hi @nhsbsa-chris,

Thanks for raising this.

The reason we use the `<span role="text"></span>` was to deal with a VoiceOver 'feature' where it reads out 'chunks' of content if wrapped in separate elements. See https://axesslab.com/text-splitting/ for an explanation.

Unfortunately the role of 'text' is not a valid role value, hence why axe flags it as an issue.
However, we took the view in this case that we would prefer VoiceOver to read content out in a way that may not cause confusion so chose this method to do that, even though it is not valid.

There's also further discussion here from Deque about adding an exception for it:
https://github.com/dequelabs/axe-core/issues/1597

**Comment by chrimesdev** [comment]
Are we happy for this issue to be closed @nhsbsa-chris @mcheung-nhs?
