### ISSUE TITLE
Header Navigation missing Active/Current CSS

### ISSUE THREAD

**Issue by mikestreety** [nhsuk/nhsuk-frontend#745]
# Bug Report

## What is the issue?

The design system has an "active/current" state on the header navigation, but I can't find any reference this in either the SCSS or Documentation.

I'm not sure if I'm missing something or something has been missed.

## What steps are required to reproduce the issue?

1. Go to https://service-manual.nhs.uk/design-system
2. Note "Design System" as a `app-header__navigation-item__item--current` class

## Is there anything else you think would be useful in recreating the issue?

![image](https://user-images.githubusercontent.com/354085/118791989-237a8c00-b88f-11eb-848a-5c8c64a37462.png)

**Comment by chrimesdev** [comment]
Hey @mikestreety this active/current style is a custom style on the NHS digital service manual, the class is prefixed with `app-`, rather than `nhsuk-`, which indicates its not coming from the frontend library.

**Comment by mikestreety** [comment]
Ah thank you!

Is there an active state or similar (or guidelines) specified for navigations or should I implement my own?

**Comment by chrimesdev** [comment]
There is an `:active` pseudo state (see screenshow below), but there no style for an active/current page (as on the service manual example) - you would need to implement your own using a similar approach to the service manual (custom style prefixed with `app-`).

![Uploading Screenshot 2021-05-19 at 11.04.17.png…]()

**Comment by chrimesdev** [comment]
Hey @mikestreety I'm going to close this issue as I'm presuming this resolved your query. If it didn't feel free to reopen it.
