### ISSUE TITLE
Search input: focus state style (desktop)

### ISSUE THREAD

**Issue by idiosyn** [nhsuk/nhsuk-frontend#768]
The search input focus state style on desktop has a thin black border. It’s different from the [standard focus state styles](https://service-manual.nhs.uk/design-system/styles/focus-state). Is there any reason for that?

![image](https://user-images.githubusercontent.com/38734779/130381615-3fe4e9a2-858d-42dd-85e2-da1c8898ff01.png)

If not, I'd like to suggest these changes:

https://github.com/nhsuk/nhsuk-frontend/blob/5ecf5c953c023f20f020a99206159248b432966b/packages/components/header/_header.scss#L355

``` scss
      border: 4px solid $nhsuk-focus-text-color;
```

https://github.com/nhsuk/nhsuk-frontend/blob/5ecf5c953c023f20f020a99206159248b432966b/packages/components/header/_header.scss#L359

``` scss
      padding: 0 9px; 
```

So the final result is:

![image](https://user-images.githubusercontent.com/38734779/130381969-1a12ba54-f063-464e-966a-b666d88f996b.png)

**Comment by chrimesdev** [comment]
Hey @idiosyn I will look into this and see if theres a reason it is this way. I may need to check with a Designer about it.

**Comment by karlgoldstraw** [comment]
Seems to work as expected in mobile breakpoints, but not on desktop. Will take a closer look. 

<img width="581" alt="Screenshot 2021-08-23 at 12 49 11" src="https://user-images.githubusercontent.com/3852457/130442313-f4cee746-1f08-48bd-9ee0-5dfa68b9004f.png">

**Comment by karlgoldstraw** [comment]
@chrimesdev I've had a look around at this and can find absolutely nothing stating that this was done for a reason, so please can we set it up as a bug to be fixed as suggested by @idiosyn above? 

Or @idiosyn if you'd like to make pull request of the changes?
