### ISSUE TITLE
Text alignment override class

### ISSUE THREAD

**Issue by teodorastraianu1** [nhsuk/nhsuk-frontend#789]
# Bug Report

## What is the issue?

Related issue: https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/297

We need a new override class for text alignment. Normally text needs to be aligned to the left (and it is by default in the prototype kit), but there are a few exceptions. (e.g. languages that run right to left, such as Arabic, when text needs to be right-aligned).

We are currently working on publishing guidance in the service manual explaining text should be left aligned unless it is an exception and we need a new override class to support those exceptions.

To support this guidance we only need an override class for right-alignment, but I see GOV's approach was creating an override class for left, center or right: https://github.com/alphagov/govuk-frontend/pull/2339

I think this would be a better approach, in case we ever need to suggest aligning text to left or center. 

## What steps are required to reproduce the issue?

- Create override classes for aligning text to left, center and right.
- Publish those classes in the frontend.

## What was the environment where this issue occurred?

* Device: n/a
* Operating System: n/a
* Browser: n/a
* Browser version: n/a
* NHS.UK frontend package version: n/a
* Node version: n/a
* npm version: n/a

**Comment by henocookie** [comment]
@DomBaker or @wa-rren-dev please could one of you check the PR is good to merge? @mcheung-nhs has already accepted the review but just want one more check ideally.

Then we will have to update the nhsuk-frontend version for the service manual app to update the text-alignment example to use the nhsuk-frontend text-alignment class which will allow us to be able to remove the custom CSS in the service manual app.
