### ISSUE TITLE
Don’t disallow legitimate “special” characters

### ISSUE THREAD

**Issue by klmr** [nhsuk/nhsuk-frontend#799]
# Bug Report

## What is the issue?

Certain NHS web forms disallow an excessive list of “special” characters. This makes it harder to write concise, understandable messages, and likely serves no real purpose (I realise that the intent is likely to make injection attacks harder. However, it might be worth revisiting this since (a) the list is missing other special characters frequently used in injection attacks, and (b) the current list massively impacts usability). In particular, the forbidden characters make it impossible to include URIs into the message. This prevents users e.g. from referring to other NHS resources in their report. This seems especially problematic.

Furthermore, the subsequent error message does not indicate *which* forbidden character was used, or where. This forces the user to manually search through the entire list of special characters to fix the issue.

## What steps are required to reproduce the issue?

1. Go to https://enquiries.test-and-trace.nhs.uk/s/
2. Go on “Start Now”
3. Select “Complaint”
4. Select “Symptoms and testing”
5. Fill the form, including special characters in the enquiry text
6. Go on “Send complaint”

## What was the environment where this issue occurred?

<details>

* Device: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
* Operating System: 10.14.6 (18G9323)
* Browser: Google Chrome
* Browser version: 96.0.4664.55

</details>

## Is there anything else you think would be useful in recreating the issue?

Actual text which originally triggered the issue (I’ve highlighted the special characters, which the error message doesn’t):

> The extraction buffer tubes on a recent lateral flow test kit were all too thin, and were cracked<kbd>/</kbd>torn before usage. Careful usage was still possible, but there was a risk of spillage<kbd>/</kbd>contamination. This issue is likely widespread<kbd>:</kbd> I have noticed thin-walled tubes in all previous test kits from the same provider (Flowflex).

Error message screenshot:

![Screenshot 2021-12-03 at 09 10 34](https://user-images.githubusercontent.com/38931/144580909-b5d23b9e-5459-4df4-bab4-e9b28675072d.png)

**Comment by chrimesdev** [comment]
Whilst this is a problem across a number of services. Form validation rules are set within the individual applications (usually on the backend, rather than frontend), they are not set not centrally by the nhsuk-frontend library. The nhsuk-frontend library just contains the styling and JavaScript logic for focusing the error inputs on page load.

Saying this, guidance could possibly be added to the form element components on the NHS digital service manual to help encourage teams not to do this.

**Comment by henocookie** [comment]
Thanks for sharing this @klmr. From a quick look, I think this may be a restriction of just the test-and-trace.nhs.uk website. I have tried the same message with the special characters you shared in the contact form on nhs.uk and didn't get the error

**Comment by henocookie** [comment]
> Saying this, guidance could possibly be added to the form element components on the NHS digital service manual to help encourage teams not to do this.

@sarawilcox do you remember any of the forms guidance work that was done with Caroline Jannet and if anything covered guidance around special character restrictions?

**Comment by klmr** [comment]
@henocookie Thanks for checking. I was wondering whether that would be the case but didn’t want to submit spurious messages on other NHS forms (in case the form accepted and submitted my message).

Feel free to close this issue and/or move it to a more appropriate repo.

**Comment by henocookie** [comment]
> @henocookie Thanks for checking. I was wondering whether that would be the case but didn’t want to submit spurious messages on other NHS forms (in case the form accepted and submitted my message).
> 
> Feel free to close this issue and/or move it to a more appropriate repo.

Thanks @klmr, I have [opened a new issue](https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/404) in the service manual community backlog repo to look into adding/improving guidance around validation for text input and text area components for teams that use them.

**Comment by sarawilcox** [comment]
No @henocookie, don't think we have anything in the forms guidance. Would be good to collect insight into validation issues/solutions in the new issue.
