### ISSUE TITLE
Footer text/bg colour combination fails contrast checks at AAA

### ISSUE THREAD

**Issue by andymantell** [nhsuk/nhsuk-frontend#805]
The colour combination of #D8DDE0 background and #4C6272 foreground fails AAA at small font sizes (Based on https://webaim.org/resources/contrastchecker/). This is in violation of the guidance set out in the NHS service manual.

![image](https://user-images.githubusercontent.com/134642/148382727-2446d338-811b-43c3-9131-c119a3095887.png)

![image](https://user-images.githubusercontent.com/134642/148383039-3cd2331d-021f-4e04-a209-b5ca70d71a49.png)

We should consider picking a darker colour to meet the AAA requirements.

**Comment by BrieWhyatt** [comment]
NHS.UK's Information Architecture team have recently updated the footer to contain links in the same style as the rest of the site. We have also grouped the links logically, making the footer more compliant to the AA standard.
![footer-post-review](https://user-images.githubusercontent.com/55788270/148781386-f274667f-8934-45d9-9ab6-78215cf20914.png)
 
However, this week, we are also iterating the footer to make the links a darker blue (#003087 - still an NHS brand guideline colour), the Crown copyright notice a black (#231F20), all with a background of pale grey (#D8DDDF).
In turn, we will feed these colour alterations into relevant components on the frontend and service manual backlogs. But, seeing as the previous footer had different colour treatments for the links, I see no objections to the colour iterations being a permanent fixture of the new footer.
![AAA-footer](https://user-images.githubusercontent.com/55788270/148781813-ec19b9d7-772e-4f51-8730-27c47deac45e.png)

**Comment by roshaanbajwa** [comment]
There is ongoing work to update the header and footer in the frontend library, and part of this will involve updating the footer to the 2nd iteration mentioned above by Brie. I have linked the relevant branch and the current timeline for the corresponding release is the end of August 2023.
