### ISSUE TITLE
Hyperlink Background on Focus hinders readability due to lack of padding

### ISSUE THREAD

**Issue by andrew-nhsbt** [nhsuk/nhsuk-frontend#810]
## What is the issue?
When a hyperlink has focus, the yellow background has little to no padding left or right, meaning the background edge encroaches on the first and final letters of the hyperlink text, hindering legibility.

### Example 1:
![image](https://user-images.githubusercontent.com/103182752/162171138-39265886-a51b-4db6-a861-cf12730f825e.png)

### Example 2:
![image](https://user-images.githubusercontent.com/103182752/162171243-014d5b1b-b591-4cf2-874a-026975546b82.png)

## What steps are required to reproduce the issue?
1. Open a website which uses the NHS Design System
2. Navigate to a page that has hyperlinks within the body text
3. Tab through the page until the hyperlink has focus
4. Observe the focussed hyperlink
**EXPECTED RESULT:** The highlighting should not encroach on or hinder readability of the link text
**ACTUAL RESULT:** The highlighting edge butts up against the some letters (e.g. t) and leaves a negligible space with others (e.g. N).

## Suggested resolution
If the styling of the a element was updated to give it left-right padding, which is then cancelled out with an equivalent negative margin, e.g.: (changes highlighted in yellow):
![image](https://user-images.githubusercontent.com/103182752/162172507-c4b92880-bb55-43ce-ae43-27c7eee38798.png)

Then all focussed hyperlinks would have a minimum clear space between the first/last letter and the edge of the highlighting,

### Example 1:
![image](https://user-images.githubusercontent.com/103182752/162172625-23e2d93c-20df-4ac6-b93a-b1ac02409bbc.png)

### Example 2:
![image](https://user-images.githubusercontent.com/103182752/162172701-b3e33759-dc33-4d6c-851d-4941fef83276.png)

**Comment by DomBaker** [comment]
Hi Andrew, thanks for the contribution. I've put this forward to our lead service designer and accessibility lead, after evaluating the raised issue it's been agreed that this is expected behaviour. Any evidence of this impeding a user's ability to read the text would be greatly appreciated.
