### ISSUE TITLE
Interactive Controls with Focus - No distinction between hover/not-hovered

### ISSUE THREAD

**Issue by andrew-nhsbt** [nhsuk/nhsuk-frontend#812]
## What is the issue?

Only distinction between focussed elements, and focussed elements being hover over is pointer change, which is hard to discern depending on OS/device settings.

## What steps are required to reproduce the issue?

1. Open a website which uses the NHS design system using a device with a pointer (i.e. not a phone/tablet)
2. Use tab to navigate down the interactive controls on the page
3. Once a button or hyperlink has focus, hover over the control
**EXPECTED RESULT:** The fact the control is under the mouse pointer (therefore will action when clicked) should be visually distinct from it un-hovered state
**ACTUAL RESULT:** The only visual distinction is the mouse pointer, which is subtle, and could vary depending on OS/Device settings.

## What was the environment where this issue occurred?
Windows 10 device with a mouse

## Is there anything else you think would be useful in recreating the issue?
Link with focus, no hover:
![image](https://user-images.githubusercontent.com/103182752/162568801-de7d16c9-1527-4404-a563-9e3396b37c3d.png)

Link with focus + hover:
![image](https://user-images.githubusercontent.com/103182752/162568808-56a188b2-64c4-4aaa-a2db-16d72ed76756.png)

Link without focus, no hover:
![image](https://user-images.githubusercontent.com/103182752/162568827-48debb52-ea1c-4024-a2ab-faf617789172.png)

Link without focus + hover:
![image](https://user-images.githubusercontent.com/103182752/162568845-ab7b80b7-b6be-4940-b38a-040dcdcb6c9d.png)

**Comment by DomBaker** [comment]
Hi Andrew, thanks for the contribution, I've put this forward to our lead service designer and accessibility lead, after evaluating the raised issue it's been agreed that this is expected behaviour. We'd love to see and or hear any evidence from users experiencing an issue with this or being a blocker to them clicking a link. Thanks once again for the contribution.
