### ISSUE TITLE
Do not quote nunjucks params in examples

### ISSUE THREAD

**Issue by fofr** [nhsuk/nhsuk-frontend#855]
Nunjucks are unnecessarily quoted in the design system examples:

<img width="790" alt="Screenshot 2023-02-09 at 08 04 07" src="https://user-images.githubusercontent.com/319055/217752940-7ca30f8d-daf1-4aa7-8444-d004a5022045.png">

This should be written as:

```nunjucks
{{ errorSummary({
  titleText: "There is a problem",
  descriptionText: "Describe the errors and how to correct them",
  errorList: [
    {
      text: "Date of birth must be in the past",
      href: "#example-error-1"
    }
  ]
}) }}
```

This would be inline with the GOV.UK design system documentation:
<img width="797" alt="Screenshot 2023-02-09 at 08 04 00" src="https://user-images.githubusercontent.com/319055/217753124-46894e2a-993b-4e9b-8154-0dbf8172f702.png">

I'm happy to raise a PR for this if we're happy to make this change.

**Comment by andymantell** [comment]
I don't mind too much either way, so I'd be happy enough for these to be unquoted personally. I see govuk did it here, and consistency with them is good:

https://github.com/alphagov/govuk-design-system/commit/73d7abc7562c50e2b456506274ca982fbfcf356f

If you wanted to open a PR, please branch off #831 (`alpha-v7`) and raise a pull request against that branch. That branch has introduced Prettier, so I'd rather we didn't make any widespread formatting changes to the main branch at the moment to avoid merge conflicts. Thanks!

**Comment by roshaanbajwa** [comment]
Closing as this is merged into service manual main
