### ISSUE TITLE
Details and Expander and the `open` param

### ISSUE THREAD

**Issue by fofr** [nhsuk/nhsuk-frontend#856]
# Bug Report

## What is the issue?

The documentation for Expander says:

<img width="779" alt="Screenshot 2023-02-09 at 08 38 30" src="https://user-images.githubusercontent.com/319055/217760303-a9f7200c-3667-49bc-aeac-d36dd30ad515.png">

https://service-manual.nhs.uk/design-system/components/expander

However, if you try to use the expander with the open param nothing happens. This is because the details template does not reference it:

https://github.com/nhsuk/nhsuk-frontend/blob/main/packages/components/details/template.njk

## Suggested fix

Suggestion is to bring the details element inline with the GOV.UK one by adding this line (and then update details component documentation):

```diff
-{%- for attribute, value in params.attributes %} {{attribute}}="{{value}}"{% endfor %}>
+{%- for attribute, value in params.attributes %} {{attribute}}="{{value}}"{% endfor %} {{- " open" if params.open }}>
```

https://github.com/alphagov/govuk-frontend/blob/main/src/govuk/components/details/template.njk

The JS to handle this is already present:
https://github.com/nhsuk/nhsuk-frontend/blob/main/packages/components/details/details.js#L41-L61

**Comment by andymantell** [comment]
Good spot! I suspect not many people do this and simply no-one's noticed yet. Fix looks simple and sensible - I'd be happy for this to go straight to main and bypass the alpha-v7 branch, _just in case_ it doesn't get merged and we end up doing another 6.x release

**Comment by andymantell** [comment]
Thanks again for this @fofr. This will land in the next release which should be happening "soon"
