### ISSUE TITLE
Deprecation Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

### ISSUE THREAD

**Issue by palanisamy-emis** [nhsuk/nhsuk-frontend#880]
# Bug Report

## What steps are required to reproduce the issue?

"We are in the process of constructing the React app using the configuration outlined below. However, during our attempt to serve the application, we encountered a plethora of warnings related to the nhsuk frontend package. We would greatly appreciate any assistance or insights that anyone could provide to address this matter."

## What was the environment where this issue occurred?

Include the following as a minimum e.g.
* Device: Windows Surface Pro 4
* Operating System: ubuntu 20.04
* Browser: Google Chrome
* Browser version: 115.0.5790.110
*
* NHS.UK frontend package version: 5.2.0
* Node version: v16.19.0
* npm version: 8.19.3

## Is there anything else you think would be useful in recreating the issue?

![image](https://github.com/nhsuk/nhsuk-frontend/assets/70691178/60a53c37-c5ff-4acc-b4df-79eef10474f6)
![image](https://github.com/nhsuk/nhsuk-frontend/assets/70691178/49067f5d-469b-4d94-99ae-68d3a232f553)

**Comment by andymantell** [comment]
This should be fixed in the 7.x releases of nhsuk-frontend. Is there a specific reason you are using 5.2.0 which is from September 2021?

**Comment by andymantell** [comment]
Closing this for now. Feel free to reopen if you believe it to be an issue in current versions of nhsuk-frontend.
