### ISSUE TITLE
Header navbar with too many/too few items

### ISSUE THREAD

**Issue by tvararu** [nhsuk/nhsuk-frontend#897]
# Bug Report

The navigation bar in the header overflows when there are too many items, causing the right-most child to break out of the grid of the page. When there are few items, like 2, the items are displayed on opposite sides of the navigation bar, with empty space between them, which does not look ideal.

## What is the issue?

I'll share some screenshots:

### Too many items

![image](https://github.com/nhsuk/nhsuk-frontend/assets/1650875/3e41634b-7a01-4c4b-b2c8-6466e58e5e3f)

### Too few items

![image](https://github.com/nhsuk/nhsuk-frontend/assets/1650875/8c210e79-e6dc-4e88-b606-75c4b0cb1888)

## What steps are required to reproduce the issue?

Go to https://nhsuk.github.io/nhsuk-frontend/components/header/header-service-name-with-nav.html to see an example with too many items. Edit the DOM using the inspector to remove items to see it with too few.

## What was the environment where this issue occurred?

* Device: Framework Laptop
* Operating System: Linux
* Browser: Firefox 118, Chrome 117
* NHS.UK frontend package version: v8.0.1 (assumed to be deployed on https://nhsuk.github.io/nhsuk-frontend/)
* Node version: Assumed to be mentioned in this repo
* npm version: Assumed to be mentioned in this repo

## Is there anything else you think would be useful in recreating the issue?

For our service we ended up writing a few CSS overrides, mainly using `justify-content: flex-end` because we use the navigation bar for current user email and a sign out link, only two items:

![image](https://github.com/nhsuk/nhsuk-frontend/assets/1650875/41eb23f5-0257-4d61-96d8-998a5758ff1c)

**Comment by roshaanbajwa** [comment]
Thanks for flagging this issue Theodor, we're working on a few other issues with the new header components so will add this to our current sprint 👍

**Comment by sarawilcox** [comment]
Is this resolved now, @roshaanbajwa? Can we close the issue? Thanks.

**Comment by roshaanbajwa** [comment]
> Is this resolved now, @roshaanbajwa? Can we close the issue? Thanks.

This will be closed in the next frontend release @sarawilcox

**Comment by sarawilcox** [comment]
Fixed in latest release,
