### ISSUE TITLE
Header/Footer samples on component site out of date with latest compiles CSS

### ISSUE THREAD

**Issue by kynrai** [nhsuk/nhsuk-frontend#899]
# Bug Report

## What is the issue?

The NHS component library has sample headers and footers https://service-manual.nhs.uk/design-system/components/header
Theres are out of date with the latest 8.0.1 compiled CSS.

## What steps are required to reproduce the issue?

Try the latest styles with the sample header code

## What was the environment where this issue occurred?

* Device: Apple M1 Pro
* Operating System: Mac OS
* Browser: Chrome
* Browser version:
* NHS.UK frontend package version: 8.0.1 
* Node version: N/A
* npm version: N/A

## Is there anything else you think would be useful in recreating the issue?

<img width="1076" alt="Screenshot 2023-10-18 at 14 12 27" src="https://github.com/nhsuk/nhsuk-frontend/assets/8189495/53d89435-1fcb-4baa-a5e3-40ee4d28dafb">

**Comment by roshaanbajwa** [comment]
Hi Steven, thanks for submitting this issue. We are currently updating the service manual to version 6.0.0, with the release scheduled this week which will address this issue and keep the Service Manual and Frontend Library inline with each other :)

**Comment by roshaanbajwa** [comment]
Hi Steven, I'm closing this issue as the service manual release is live here: https://github.com/nhsuk/nhsuk-service-manual/releases/tag/v6.0.0 and it's now up to date. Thanks :)
