### ISSUE TITLE
'Primary Card (With Chevron)' issue while hovering over chevron image

### ISSUE THREAD

**Issue by OWMAS** [nhsuk/nhsuk-frontend#904]
# Bug Report

## What is the issue?

When clicking the chevron image on a 'Primary Card (With Chevron)' card element the link isn't focused. Able to work around using 'pointer-events: none'.

## What steps are required to reproduce the issue?

1: Create a 'Primary Card (With Chevron)' element as documented [here](https://service-manual.nhs.uk/design-system/components/card)

2: Attempt to perform the action described by the card while the mouse cursor is hovered over the chevron image.

## What was the environment where this issue occurred?

Device: Dell Latitude 5420
Operating System: Windows 10
Browser: Firefox and Google Chrome
Versions: Firefox 119.0.1, Google Chrome 119.0.6045.160

NHS.UK frontend package version: 8.0.2
Node version: v19.5.0
npm version: 9.3.1

## Is there anything else you think would be useful in recreating the issue?

The issue also seems to be occuring on the [documentation page](https://service-manual.nhs.uk/design-system/components/card) as you are able to see by the lack of highlighting while hovering over the chevron image.

**Comment by roshaanbajwa** [comment]
Hi Owen, thanks for submitting this issue. Once I've checked with the content team that this is indeed the desired action, I'll get the fix merged :)

**Comment by roshaanbajwa** [comment]
Fix is now merged ✅
