### ISSUE TITLE
Back links - probably shouldn't have visited colour styles when hovered.

### ISSUE THREAD

**Issue by edwardhorsford** [nhsuk/nhsuk-frontend#955]
# Bug Report
Back links show visited colours when hovered. I'm not sure this is expected or intended? I'd treat them as special UI that does not get visited styles.

![Screenshot 2024-05-28 at 16 29 49](https://github.com/nhsuk/nhsuk-frontend/assets/2204224/077c480d-dfd0-427d-b820-a7d6fc2719c3)

There's similar for the design system nav itself. There's no visited styles when not hovered which makes me think they've been disabled - but accidentally remain on hover.

**Comment by frankieroberto** [comment]
@edwardhorsford I don’t quite follow this. On hover the back links gain an underline and change colour to #7c2855 in the same way as regular links, but that doesn’t seem to be related to the 'visited' link style at all, which is a more subtle colour change to #330072, and doesn’t apply to the back links?

**Comment by edwardhorsford** [comment]
Yeah I now think this is intentional - they have a maroon colour on hover. Closing!
